---
title: "TP1 Análisis Exploratorio de Datos"
author: "Gonzalo & Octavio"
date: "April 11, 2018"
output: html_document
---

## Inicialización

```{r inicializacion, }
library(tidyverse)
library(knitr)
```

```{r funciones}
llenarAlbum <- function (figuritas_album = 500, figuritas_sobre = 5, n_albumes = 1, sobres_con_repetidas = F, pesos = rep(1, figuritas_album)) {
  # figuritas_album:= cantidad de figuritas distintas del album
  # figuritas_sobre:= cantidad de figuritas por sobre
  # n_albumes:= cantidad de albumes que se pretende completar
  #   Un unico coleccionista que rellena n albumes es una buena aproximacion a
  #   mercado de n coleccionistas "altruistas", que intercambian toda figurita repetida.
  # sobres_con_repetidas:= ¿Pueden los sobres contener figuritas repetidas?
  # pesos:= (opcional) Pesos para la "dificultad relativa" de cada figurita
  
  if (figuritas_album < 1) {
    print(paste("Pruebe con una cantidad positiva de figuritas por album."))
    return()
  }
  
  album <- rep(0, figuritas_album)
  n_sobres <- 0
  
  while(!all(album >= n_albumes)) {
    sobre <- sample(
      1:figuritas_album,
      figuritas_sobre,
      replace = sobres_con_repetidas,
      prob = pesos
    )
    
    album[sobre] <- album[sobre] + 1
    n_sobres <- n_sobres + 1
  }
  
  return(n_sobres)
}

# k <- rep(c(5,10,50,100), 1000)
# obs <- map(k, ~replicate(., llenarAlbum()))
# data_frame(k = k,
#           obs = obs) %>%
#  mutate(a_k = map_dbl(obs, mean)) -> datos
# Dependiendo de si se quiere generar de cero el análisis o se prefiere usar
# los datos precalculados se deberán comentar alguna de las siguientes líneas
# save(datos, file='TP1.RData')
# rm(datos)
load('TP1.RData')
```

```{r generar_datos}
```

```{r boxplot}
ggplot(data = datos, mapping = aes(x = k, y = a_k, fill = factor(k))) + geom_boxplot()
```

```{r histograma}
ggplot(datos, aes(x = a_k, group = k, fill = factor(k))) +
  geom_histogram(bins = 70) +
  facet_grid(k ~ .)
```

```{r}
datos %>%
  group_by(k) %>%
  summarise(
    media_ak = mean(a_k),
    mediana_ak = median(a_k),
    media_ak_01 = mean(a_k, trim = 0.1),
    var_ak = var(a_k),
    iqr_ak = IQR(a_k),
    mad_ak = mad(a_k)
  ) -> estadisticos_resumen
kable(estadisticos_resumen)
```
